/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Simulador_imagenes;
import Main.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args){
        
        Menu menu = new Menu();
        
        while(!menu.getSalirMenu()){
            menu.ejecutarMenu();
        
        }
    }
}
